name: maidscc_todos_app
description: "Todos app that allows users to manage their todos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localization: 
  flutter_bloc: 
  bloc_concurrency:
  equatable: 
  dartz:
  get_it:
  internet_connection_checker:
  http:
  shared_preferences:
  go_router: ^6.5.0
  flutter_screenutil:
  path:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat.ttf